apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: projectory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password-secret
                  key: mysql-root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            # Commented out for testing without the custom config file
            # - name: mysql-config
            #   mountPath: /etc/mysql/my.cnf
            #   subPath: my.cnf
          securityContext:
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-scripts
          configMap:
            name: mysql-init-script
        # Temporarily comment out mysql-config volume
        # - name: mysql-config
        #   configMap:
        #     name: mysql-config
