apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: projectory
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001   # Exposed service port
      targetPort: 8080  # Container's port
  type: ClusterIP