apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: projectory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-pod
          image: salehaa/projectory-backend:latest
          imagePullPolicy: Always  
          ports:
            - containerPort: 8080