apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: projectory
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306        # Service port for internal access
      targetPort: 3306  # Container port for MySQL
  type: ClusterIP     # Expose service within the cluster
